import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Download continuous front-month Nasdaq-100 Futures data
ticker = "NQ=F"
data = yf.download(ticker, start="2023-01-01", end="2026-01-01")

# Clean multi-level index columns if generated by yfinance
if isinstance(data.columns, pd.MultiIndex):
    data.columns = data.columns.get_level_values(0)

# Isolate close price for math operations
df = data[['Open', 'Close']].copy()

# 2. Mathematical Signal Generation (20-Day Simple Moving Average)
df['Signal_MA'] = df['Close'].rolling(window=20).mean()

# Position: 1 (Long) if Close > MA, else 0 (Flat/Cash)
df['Position'] = np.where(df['Close'] > df['Signal_MA'], 1, 0)

# CRITICAL: Shift positions by 1 day to execute on NEXT open, removing lookahead bias
df['Position'] = df['Position'].shift(1)

# 3. Strategy Returns Calculation
df['Market_Returns'] = df[('Close') - df('Open') / df('Open')].pct_change()
df['Strategy_Returns'] = df['Market_Returns'] * df['Position']

# Calculate compounded cumulative returns
df['Cumulative_Market'] = (1 + df['Market_Returns'].fillna(0)).cumprod() - 1
df['Cumulative_Strategy'] = (1 + df['Strategy_Returns'].fillna(0)).cumprod() - 1

# 4. Performance Visualization
plt.figure(figsize=(12, 6))
plt.plot(df['Cumulative_Market'] * 100, label='Buy and Hold Nasdaq Futures (%)', color='gray', alpha=0.7)
plt.plot(df['Cumulative_Strategy'] * 100, label='Quant MA Strategy (%)', color='blue', linewidth=2)
plt.title('Nasdaq Futures: Simple Quant Strategy Backtest')
plt.xlabel('Date')
plt.ylabel('Cumulative Return (%)')
plt.legend()
plt.grid(True)
plt.show()

print(f"Final Market Return: {df['Cumulative_Market'].iloc[-1] * 100:.2f}%")
print(f"Final Strategy Return: {df['Cumulative_Strategy'].iloc[-1] * 100:.2f}%")